#!/bin/sh

set -e

if [ ! -e /usr/lib/libqhtmlparser.so.1.0.0 ]
    then
        ln -s /opt/lib/libqhtmlparser.so.1.0.0 /usr/lib/libqhtmlparser.so.1.0.0
        ln -s /opt/lib/libqhtmlparser.so.1.0.0 /usr/lib/libqhtmlparser.so
        ln -s /opt/lib/libqhtmlparser.so.1.0.0 /usr/lib/libqhtmlparser.so.1
        ln -s /opt/lib/libqhtmlparser.so.1.0.0 /usr/lib/libqhtmlparser.so.1.0
fi

exit 0
